### ISSUE TITLE
[Suggestion] bring goldeneye source to steam

### ISSUE THREAD

**Issue by 0xBADEAFFE** [goldeneye-source/ges-code#20]
@droidmonkey Why not adding ges to steam greenlight, as soon as the source sdk 2013 port is ready? This would also revive the mod.

**Comment by droidmonkey** [comment]
There are various legal (copyright) and logisitical hurdles for us to ever consider this. As it stands we are not continuing the port to SDK2013 at this time.

**Comment by 0xBADEAFFE** [comment]
@droidmonkey Thank you for your quick reply. I think this is sad because ges is a great mod. What legal problems are you exactly facing when releasing it as free mod on steam?
