### ISSUE TITLE
CaptureArea zones collide with rockets

### ISSUE THREAD

**Issue by ThomasSumner** [goldeneye-source/ges-code#21]
A CaptureArea, e.g. the ones used in Uplink, collide with rockets. The rockets explode within and around  the areas (e.g. firing a rocket launcher within an area instantly kills you). Other projectiles, such as grenades, grenade launcher rounds and mines do not have this problem.

**Comment by ThomasSumner** [comment]
[demo.zip](https://github.com/goldeneye-source/ges-code/files/287704/demo.zip)

**Comment by droidmonkey** [comment]
Corrected in v5.0
