### ISSUE TITLE
Question - does this even build on Debian / SteamOS Linux?

### ISSUE THREAD

**Issue by ElectricPrism** [goldeneye-source/ges-code#22]
I was wondering if anyone has tried lately it seems the repository has gone cold for some time.

Also what is the status, is it working or not working, or is this even the area that development is taking place or just a mirror?

**Comment by droidmonkey** [comment]
https://github.com/goldeneye-source/ges-code#how-to-build

**Comment by ElectricPrism** [comment]
Thank you, I'll close this issue as it seems confirmed that it will build, I am now trying out the instructions.

I will update my progress on this thread here:
https://github.com/goldeneye-source/ges-code/issues/23
