### ISSUE TITLE
Is it documented what characters do what colors when using ^ ?

### ISSUE THREAD

**Issue by ChildishGiant** [goldeneye-source/ges-code#29]
`^rR^oa^yi^gn^bb^po^rw` 
Will produce this:
![image](https://user-images.githubusercontent.com/13716824/27651337-de504800-5c2f-11e7-8c47-9b402ffb2a86.png)

R for red
O for orange 
etc...

Is it documented what does what?

**Comment by ghost** [comment]
This is what you want: https://wiki.geshl2.com/hudcolor

:)
